# Generated by Django 5.0.2 on 2024-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_artist_listeners"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["-listeners", "name"]},
        ),
    ]
