# Generated by Django 5.0.2 on 2024-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_alter_artist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
