# Generated by Django 5.0.2 on 2024-02-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_alter_artist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["-listeners", "name"]},
        ),
    ]
