# Generated by Django 5.0.2 on 2024-03-03 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_alter_artist_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={"ordering": ["-monthly_listeners", "name"]},
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="listeners",
            new_name="monthly_listeners",
        ),
        migrations.AddField(
            model_name="artist",
            name="bio",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="subscribers",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="verified",
            field=models.IntegerField(
                choices=[(0, "unverified"), (1, "verified")], default=0
            ),
        ),
    ]
