# Generated by Django 5.0.1 on 2024-03-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pfp',
            field=models.ImageField(height_field=10, null=True, upload_to='', width_field=10),
        ),
    ]
