# Generated by Django 5.0.2 on 2024-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0007_artist_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="pfp",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
