# Generated by Django 5.0.2 on 2024-03-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0008_alter_artist_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="pfp",
            field=models.ImageField(default="default_image.jpg", upload_to=""),
        ),
    ]
