# Generated by Django 5.0.2 on 2024-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0011_alter_song_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="cover",
            field=models.ImageField(
                default="default__cover_image.jpg", null=True, upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="type",
            field=models.CharField(
                choices=[("Single", "Single"), ("EP", "Ep"), ("Album", "Album")],
                default="Single",
                max_length=50,
            ),
        ),
    ]
