# Generated by Django 5.0.2 on 2024-06-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0013_playlist_alter_artist_options_alter_artist_bio_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="users.profile",
            ),
        ),
    ]
