# Generated by Django 5.0.2 on 2024-06-09 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0014_playlist_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist",
            old_name="user",
            new_name="profile",
        ),
    ]
